config/routes.rb
Sportcv::Application.routes.draw do
  

  get 'auth/:provider/callback', to: 'sessions#create'

  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get "static/index"

  resources :roles

  resources :sports

  resources :teams

  resources :players do
    member do
      get 'show_connections'
    end
  end

  resources :player_team_relations

  resources :managers do
    member do
      get 'show_connections'
    end
  end

  resources :people

  resources :extras

  resources :frontpage, only: [:index]  do
    collection do
      get 'first_time_user'
    end
  end

  root :to => "frontpage#index"

end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :managers, :dependent => :destroy
  has_many :players, :dependent => :destroy

  def is_a_new_user?
     self.players.empty? && self.managers.empty?
  end

   def is_a_player?
     not self.players.empty?
  end

   def is_a_manager?
     not self.managers.empty?
   end

  def self.from_omniauth(auth) 
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |person|
      person.provider = auth.provider
      person.uid = auth.uid
      person.first_name = auth.info.first_name
      person.last_name = auth.info.last_name
      person.image_url = auth.info.image
      person.birthday = auth.extra.raw_info.birthday if auth.extra.raw_info.birthday.present?
      person.email = auth.extra.raw_info.email
      person.oauth_token = auth.credentials.token
      person.oauth_expires_at = Time.at(auth.credentials.expires_at)
      person.save!
    end
  end


 


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :birthday, :email, :height, :weight, :phone, :position)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
    
  <div class="control-group">
    <%= f.label :birthday, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :birthday, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :height, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :height, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight , :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:birthday) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:height) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.first_name %></td>
	<td><%= person.last_name %></td>
        <td><%= person.birthday %></td>
        <td><%= person.email %></td>
        <td><%= person.phone %></td>
        <td><%= person.height %></td>
        <td><%= person.weight %></td>
        <td><%= person.position %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :destroy,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @person.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @person.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birthday) %>:</strong></dt>
  <dd><%= @person.birthday %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @person.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height) %>:</strong></dt>
  <dd><%= @person.height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @person.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @person.position %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'destroy',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>