config/routes.rb
Sportcv::Application.routes.draw do
  

  get 'auth/:provider/callback', to: 'sessions#create'

  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get "static/index"

  resources :roles

  resources :sports

  resources :teams

  resources :players do
    member do
      get 'show_connections'
    end
  end

  resources :player_team_relations

  resources :managers do
    member do
      get 'show_connections'
    end
  end

  resources :people

  resources :extras

  resources :frontpage, only: [:index]  do
    collection do
      get 'first_time_user'
    end
  end

  root :to => "frontpage#index"

end

app/models/manager.rb
class Manager < ActiveRecord::Base
	belongs_to :person	
	belongs_to :team, autosave: true


	def new_connections
		self.team.player_team_relations.find_all { |rel| !rel.player_accepted}
	end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy, :show_connections]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to controller: 'teams', action: 'new', mg: @manager  }
        format.json { render action: 'show', status: :created, location: @manager }
      else
        format.html { render action: 'new' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :no_content }
    end
  end

  def show_connections
    @connections = @manager.new_connections
    @manager.has_message = false
    @manager.save
    respond_to do |format|
      format.html { render 'connections/show_connections'} 
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:person_id)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_for @manager, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :person_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :person_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                managers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/managers/index.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:person_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= link_to manager.id, manager_path(manager) %></td>
        <td><%= manager.person_id %></td>
        <td><%=l manager.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_manager_path(manager), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      manager_path(manager),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_manager_path,
            :class => 'btn btn-primary' %>

app/views/managers/new.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/managers/show.html.erb
<%- model_class = Manager -%>
<div class="player_header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:person_id) %>:</strong></dt>
  <dd><%= @manager.person_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              managers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_manager_path(@manager), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              manager_path(@manager),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>