config/routes.rb
Sportcv::Application.routes.draw do
  

  get 'auth/:provider/callback', to: 'sessions#create'

  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get "static/index"

  resources :roles

  resources :sports

  resources :teams

  resources :players do
    member do
      get 'show_connections'
    end
  end

  resources :player_team_relations

  resources :managers do
    member do
      get 'show_connections'
    end
  end

  resources :people

  resources :extras

  resources :frontpage, only: [:index]  do
    collection do
      get 'first_time_user'
    end
  end

  root :to => "frontpage#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sportcv" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  
  </head>

  <body>
  <div id="wrap">
  <div class="navbar navbar-inverse">  
    <div class="navbar-inner">  
      
      <div class="navbar-header pull-left">
        <h3 style="color:white">Sportnection</h3>
      </div>
      <ul class="nav" style="margin-left:4%;">  

                      <li><%= link_to "Profile", player_path(current_user.players.first) if current_user.players.exists? %>
                      <%= link_to "Profile", team_path(current_user.managers.first.team) if current_user.managers.exists? %>
                       </li>  
                      <li><a href="/players">Players</a></li>  
                      <li><a href="/teams">Teams</a></li>  
      </ul>

      <ul class="nav navbar-nav pull-right">
        <% if current_user.managers.exists? %>
          <% if current_user.managers.first.has_message %>
            <% message_pic = "http://kodu.ut.ee/~vooteler/images/sulleonkiri_veel_minim.gif" %>
          <% else %>
            <% message_pic = "http://kodu.ut.ee/~vooteler/images/message.png" %>
          <% end %> 
          <li><%= link_to image_tag(message_pic, class: 'mailbox' ), main_app.show_connections_manager_path(current_user.managers.first)%></li>
        <% end %>

        <li><%= link_to "Log out",  controller: 'sessions' , action: 'destroy', id: "sign_out" %></li>  
      </ul>

    </div>  

  </div>   

  <div class="container"> 
    <div class="content">
        <%= yield %>
    </div>
  </div>  
  </div>

<!--  <footer>
    <div id="footer">
     <h2>Sportnection<h2>
    </div>
  </footer> -->


  </body>

</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sportcv" %></title>
    <%= favicon_link_tag '/assets/images/favicon.ico' %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
    <body>


      <header>
      
        <div id="h_right">
          <div id="login">
              <a href="#" class="login">Log in</a>
          </div>
        </div>

        <div id="h_left">
          <img src='http://www.fastrepair.com/wp-content/uploads/2010/11/apple_logo-120x120.jpg' alt="some_text">
        </div>

        <div id="h_middle">
            <div id="search">
                <input type="text" class="search square"><input type="button" value="Search">
            </div>
            <div id="menu">

                 <a href="default.asp">Home</a>
                 <a href="news.asp">Athletes</a>
                 <a href="contact.asp">Teams</a>
                 <a href="contact.asp">Profile</a>
                 <a href="contact.asp">Connections</a>
                 <a href="about.asp">About</a>

            </div>
        </div>

      </header>
      <div id="clear_div"></div>
      <div class="content">
        <%= yield %>
 

      </div>


       <footer>
            <div id="f_left">
              <a href="default.asp">Contact</a>
            </div>
      </footer>

    </body>
</html>

app/views/layouts/frontpage_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sportcv" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>

   <body>
         
 <div class="container-fluid" id="index">
         
         <div class="hero-unit hero_header">
            <div id="logo">
                <img src="http://kodu.ut.ee/~vooteler/images/logo_transparent_white2.png"/>
            </div>
            <h2 id="index_header">Sportnection is an online platform that helps
             players and teams find each other in a fast and efficient way that saves
             time and money. Sportnection is all about sports connections!</h2>
         </div>

<%= yield %>

<div class="column">
<!--<div class="hero-unit" id="index_footer">
    <div class="span10" id="index_footer_text">
        
    </div>
</div> -->
</div>



 </div><!-- .container -->
     
 </body>
</html>